export const SET_USER_LOADING = "SET_USER_LOADING";

export const SET_USER = "SET_USER";
export const REMOVE_USER = "REMOVE_USER";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
export const SET_USER_FAIL = "SET_USER_FAIL";
