export const SET_CONTACT_LOADING = "SET_CONTACT_LOADING";

export const ADD_CONTACT_REQUEST = "ADD_CONTACT_REQUEST";
export const ADD_CONTACT_REQUEST_SUCCESS = "GET_FOOD_IETMS_SUCCESS";
export const ADD_CONTACT_REQUEST_FAIL = "GET_FOOD_IETMS_FAIL";
