// Author - Roshil Ka Patel (B00917345)
export const SET_FOOD_LOADING = "SET_FOOD_LOADING";

export const GET_ALL_FOOD_ITEMS = "GET_ALL_FOOD_ITEMS";
export const GET_ALL_FOOD_ITEMS_SUCCESS = "GET_ALL_FOOD_ITEMS_SUCCESS";
export const GET_ALL_FOOD_ITEMS_FAIL = "GET_ALL_FOOD_ITEMS_FAIL";

export const GET_FOOD_ITEMS = "GET_FOOD_IETMS";
export const GET_FOOD_ITEMS_SUCCESS = "GET_FOOD_IETMS_SUCCESS";
export const GET_FOOD_ITEMS_FAIL = "GET_FOOD_IETMS_FAIL";

export const ADD_FOOD_ITEM = "ADD_FOOD_ITEM";
export const ADD_FOOD_ITEM_SUCCESS = "ADD_FOOD_ITEM_SUCCESS";
export const ADD_FOOD_ITEM_FAIL = "ADD_FOOD_ITEM_FAIL";

export const UPDATE_FOOD_ITEM = "UPDATE_FOOD_ITEM";
export const UPDATE_FOOD_ITEM_SUCCESS = "UPDATE_FOOD_ITEM_SUCCESS";
export const UPDATE_FOOD_ITEM_FAIL = "UPDATE_FOOD_ITEM_FAIL";

export const DELETE_FOOD_ITEM = "DELETE_FOOD_ITEM";
export const DELETE_FOOD_ITEM_SUCCESS = "DELETE_FOOD_ITEM_SUCCESS";
export const DELETE_FOOD_ITEM_FAIL = "DELETE_FOOD_ITEM_FAIL";

export const CHANGE_ACTIVATION_STATE = "CHANGE_ACTIVATION_STATE";
export const CHANGE_ACTIVATION_STATE_SUCCESS = "CHANGE_ACTIVATION_STATE_SUCCESS";
export const CHANGE_ACTIVATION_STATE_FAIL = "CHANGE_ACTIVATION_STATE_FAIL";
